---
- name: Apply Patch (Scheduled Start)
  hosts: localhost
  gather_facts: no
  vars:
    dashboard_ip: "{{ dashboard_ip | default('127.0.0.1') }}"
    ticket_id: "{{ lookup('pipe', 'uuidgen') }}"
    status_api: "http://{{ dashboard_ip }}:5000/api/status"

  tasks:
    - name: 📅 Update dashboard - Scheduled
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Scheduling"
          status: "Scheduled to start in 10 minutes"

    - name: ⏳ Wait for scheduled patch time
      pause:
        minutes: 10
        prompt: "Waiting 10 minutes before patching begins..."

    - name: ✅ Update dashboard - Patching Started
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Patching"
          status: "In Progress"

    - name: 🛠️ Simulate patching
      shell: "echo 'Patching server for ticket {{ ticket_id }}'"

    - name: ✅ Update dashboard - Patching Completed
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Patching"
          status: "Completed"
