---
- name: Apply Patch (Scheduled Start)
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    dashboard_ip: "54.162.23.213"   # override with -e if needed
    ticket_id: "{{ lookup('pipe', 'uuidgen') }}"   # can also pass from workflow
    status_api: "http://{{ dashboard_ip }}:5000/api/status"
    patch_env: "dev"
    impact: "P3"
    patch_wait_minutes: 3   # override in survey or extra vars

  tasks:
    - name: Update dashboard - Scheduled
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Scheduling"
          status: "Scheduled to start in {{ patch_wait_minutes }} minutes"
          activity: "Patching"
          impact: "{{ impact }}"
          environment: "{{ patch_env }}"
      register: scheduled_response
      failed_when: scheduled_response.status != 200

    - name: Wait for scheduled patch time
      pause:
        minutes: "{{ patch_wait_minutes }}"
        prompt: "Waiting {{ patch_wait_minutes }} minutes before patching begins..."

    - name: Update dashboard - Patching Started
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Patching"
          status: "In Progress"
          activity: "Patching"
          impact: "{{ impact }}"
          environment: "{{ patch_env }}"
      register: patching_started_response
      failed_when: patching_started_response.status != 200

    - name: Simulate patching
      shell: "echo 'Patching server for ticket {{ ticket_id }}'"

    - name: Update dashboard - Patching Completed
      uri:
        url: "{{ status_api }}"
        method: POST
        body_format: json
        body:
          ticket_id: "{{ ticket_id }}"
          stage: "Patching"
          status: "Completed"
          activity: "Patching"
          impact: "{{ impact }}"
          environment: "{{ patch_env }}"
      register: patching_completed_response
      failed_when: patching_completed_response.status != 200
